######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 2 15:03:33 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gamegui.h news.h play.h
SOURCES += gamegui.cc main.cc news.cc play.cc
